### PR TITLE
Mmansurova/abc 333

### PR DESCRIPTION
**Pull request by Mil-m**

### CODE REVIEW

**Comment by yroochun** [comment]
1. Log out Button should be displayed on all pages, not just on the user-profile page. Please have the logout button in the banner
2. If user logs out and navigate to the previous page, he can still access the user-profile page.

**Comment by yroochun** [comment]
Please review my first comment.
_1. Log out Button should be displayed on all pages, not just on the user-profile page. Please have the logout button on the banner_

The log out button should be displayed on the banner. If we are to have multiple components, we can't be expected to  copy paste the logout code on all pages

**Comment by yroochun** [comment]
Logout button shouldn't be displayed if user is already logged out

**Comment by Mil-m** [comment]
> Logout button shouldn't be displayed if user is already logged out

fixed

**Comment by Mil-m** [comment]
as I understood, we're saving user data instead of token for authentication; is it Ok?

  logInUser(user: UserCredentials): void {
    this.authService.logIn(user.username, user.password).subscribe({
      next: (data) => {
        this.authService.setLoggedInUser(data);
        this.router.navigateByUrl(`/user-profile/${data.id}`);
      },
      error: (error) => {
        console.log(error);
      }
    });
  }
  
should we change it to the token authentication?
  
https://medium.com/@bekhruz.mirtursinov/best-practices-for-managing-user-data-and-authentication-in-angularjs-applications-253c2f0687c

**Comment by yroochun** [comment]
We are already using token authentication. The userData variable contains the token. Please take a look at the HTTP interceptor and authentication guard code

**Pull request merged**
