### PR TITLE
Mmansurova/abc 338

### PR DESCRIPTION
**Pull request by Mil-m**

### CODE REVIEW

**Comment by yroochun** [comment]
1. Code was not tested. It doesn't work.

2. 2. The functionality is incorrect. The code was modified only on the front-end to hide the rows that do not belong to the logged-in PI. As a result, pagination is inconsistent, with some pages displaying 10 entries and others showing only 3 rows where records for different PIs were hidden. This creates an odd appearance overall.

3. The ticket requirements were not taken into account and implemented.

**Comment by yroochun** [comment]
The entire implementation is incorrect. Records need to be filtered on the backend rather than merely hiding their visibility on the front end.

**Comment by Mil-m** [comment]
> The entire implementation is incorrect. Records need to be filtered on the backend rather than merely hiding their visibility on the front end.

Ok, thank you for letting me know. I thought that this ticket was only about the FE changes only
I'll fix it ASAP

Regarding the pagination - I'm going to update it in another PR as we have a separate task for it (abc-341)

**Comment by Alexey-ebi** [comment]
Before code review, could I ask you to resolve all conflicts above please

**Review by Alexey-ebi — CHANGES_REQUESTED** [review]

**Comment by yroochun** [comment]
1. Existing functionality is broken

2. When creating a new tna project, we get a permission error when fetching additional participant details after selecting an existing participant

3. When editing entries, records are sometimes duplicated with the same ID

4. If user goes on edit mode for a TNA project and enters a non-existent id in the URL, they should be directed to a forbidden page. At the moment the form is still displayed

**Comment by yroochun** [comment]
The Edit button should be hidden when the entry is marked as submitted. Currently, this is not the case as demonstrated to you.

**Comment by yroochun** [comment]
Please try to ensure PRs focus on your actual work, rather than automatic IDE changes. It can be confusing to review your code otherwise.

**Pull request merged**
